# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 969bc0056c319c6e5fc7295e2b75a6625a2c3a56bf67bf48027560b08a60f61bce466789ff0ad0ac2d0bad978ca66f63376bcee89d997d64c249ae9363fc72ae

test:
  secret_key_base: d89ffbf86b9367f69ef15032d535ed94323a184e02aa27628841c916baa876b2ef21aeb651287bc903ed506c8fad5b7811b86705b651b34a2dc62276eae60fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
